train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../dataset/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-bicubic
    args:
      inp_size : 96
      gt_size: 384
      scale_max: 4
      augment: true
      sample_q: 4608
  batch_size: 8

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif
  args:
    encoder_spec:
      name: edsr-baseline-sa2
      args:
        no_upsampling: true
        slot_num: 10
        slot_iters: 3
        slot_attn_heads: 1
        slot_dim: 64
        slot_mlp_hid_dim: 64
        slot_init_mode: 'learnable'
        return_attn: False
        joint_lr_recon: False
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256, 256]
    local_ensemble: True
    feat_unfold: True
    cell_decode: True
    

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 5
epoch_save: 100

eval_bsize: 1

mode : 0
is_resume : False
resume: ./save/train_edsr-baseline-sa2-liif_bigger-image/epoch-last.pth