train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-bicubic
    args:
      inp_size : 48
      gt_size: 192
      augment: true
  batch_size: 4

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: edsr-baseline-jw2
  args:
    scale: 4
    upsample_mode: ['bicubic', 'bilinear', 'nearest']
    n_feats: 48
    n_feats_target: 32
    reproduce_layers: [3, 7, 11, 15, -1]
model_t:
  name: edsr-baseline-m
  load_dir: 'save/train_edsr-light-x1/epoch-last.pth'
  args:
    scale: 1
    upsample_mode: 'bicubic'
    reproduce_layers: [3, 7, 11, 15, -1]
loss:
  rgb: 
    type: 'l1'
    weight: 1.0
  feat: 
    type: 'mse' # 'l2' == 'mse'
    weight: 1.0


optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100

scale:
  mode: 'multi_arbitrary'
  factor_range: [1, 4]
  

is_resume : False
resume: ./save/_train_edsr-baseline-multi_jw2/epoch-last.pth